INSERT INTO specifications
    (
    id,
    year,
    engine,
    fuel_system,
    engine_alignment,
    engine_position,
    engine_valves,
    engine_displacement,
    engine_horsepower,
    bore_stroke,
    aspriation,
    compression_ratio,
    max_torque,
    transmission_offered,
    fuel_economy_combined,
    fuel_economy_highway,
    fuel_econony_city,
    fuel_range,
    fuel_capacity,
    co2_emissions,
    top_speed,
    accelerations_0_60,
    drivetain,
    body,
    width,
    height,
    length,
    front_axle,
    rear_axle,
    front_brakes_disc_type,
    rear_brakes_disc_type,
    drag_coefficient,
    front_rims_dimensions,
    rear_rims_dimensions,
    front_wheels_width,
    rear_wheels_width,
    turning_radius,
    weight_power_output,
    trunk_capacity,
    curb_weight,
    wheelbase,
    steering_type,
    front_suspension,
    rear_suspension,
    number_of_seats,
    number_of_doors,
    generation
    )
VALUES
    (
        1,
        '2014-2016',
        'N55 - Inline 6',
        'Petrol/Gas',
        'Longitudinal',
        'Front',
        24,
        '2979 cm3 or 181.8 cu-in',
        '322hp',
        '84 x 89.6 mm / 3.31 x 3.5 inches',
        'Turbo + Intercooler',
        10.2,
        '450 Nm or 331 lb.ft @ 1300-4500 rpm',
        '8 Speed automatic and 6 speed manual',
        '8.1 L/100km - 35 mpg UK / 29 mpg US',
        '6.4 L/100km - 44 mpg UK / 37 mpg US',
        '10.9 L/100km - 26 mpg UK / 22 mpg US',
        '641 Km or 398 miles',
        '52 L / 11.4 UK gallons / 13.7 US gallons',
        '189 g/Km (BMW)',
        '250 km/h or 155 Mph',
        '4.4 (s)',
        'RWD',
        'Coupe',
        '177.4 cm or 69.84 inches',
        '140.8 cm or 55.43 inches',
        '445.4 cm or 175.35 inches',
        '151.6 cm or 59.69 inches',
        '153.2 cm or 60.31 inches',
        'Vented Discs (- mm)',
        'Discs (- mm)',
        0.33,
        '225/40 R18',
        '245/35 R18',
        '7.5"',
        '8"',
        '10.9 m / 35.8 feet',
        '4.7 kg/hp',
        '390 L',
        '1530 kg OR 3373 lbs',
        '269 cm or 105.91 inches',
        'Rack and pinion Electric',
        'Independent. McPherson struts. Coil springs. Anti-roll bar.',
        'Independent. Coil springs. Anti-roll bar.',
        4,
        2,
        'f22'
);